FROM ubuntu AS checker
WORKDIR /app
RUN \
    --mount=type=cache,target=/app/cache \
    mkdir -p /app/dist && \
    cp -r /app/cache/* /app/dist

FROM scratch
WORKDIR /
COPY --from=checker /app/dist .