name: Quality Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    # branches: [ master ]
  workflow_dispatch:

jobs:
  build_docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - [
            "linux/amd64",
            "amd64",
          ]
          - [
            "linux/arm64",
            "arm64",
          ]
          - [
            "linux/arm/v7",
            "arm32v7",
          ]
          - [
            "linux/386",
            "386",
          ]
          - [
            "linux/arm/v6",
            "arm32v6",
          ]
    steps:
    - uses: actions/checkout@v4

    # - name: Set up QEMU
    #     uses: docker/setup-qemu-action@v3

    - uses: docker/setup-buildx-action@v3
      id: setup

    - name: Cache Folders
      uses: actions/cache@v4
      with:
        path: cache
        key: cache-${{ github.sha }}
        restore-keys: |
          cache-

    - name: Create folder on cache miss
      run: |
        mkdir -p cache/sub/dir
      
    - name: Check for cache after restore
      continue-on-error: true
      run: |
        ls -la
        ls -la cache
        ls -la cache/sub/dir

    - name: Clear cache 
      continue-on-error: true
      run: |
        rm -rf cache
        mkdir -p cache/sub/dir

    # not saving cache https://github.com/reproducible-containers/buildkit-cache-dance/issues/33
    # - name: inject cache folders into docker
    #   uses: reproducible-containers/buildkit-cache-dance@v3.1.2
    #   with:
    #     cache-map: |
    #       {
    #         "cache": "/app/cache/"
    #       }

    # ex: https://docs.docker.com/build/ci/github-actions/cache/
    # - name: inject cache folders into docker
    #   uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4          
    #   with:
    #     cache-source: cache
    #     cache-target: /app/cache
    
    - name: inject
      uses: docker/build-push-action@v6
      with:
        push: false
        platforms: ${{ matrix.platform[0] }}
        # do not cache layers
        # cache-from: type=local,src=.cache
        # cache-to: type=local,dest=.cache-new,mode=max
        file: Dockerfile.inject
        context: cache/sub/dir
        build-args: TARGET=/app/cache

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: false
        platforms: ${{ matrix.platform[0] }}
        # do not cache layers
        # cache-from: type=local,src=.cache
        # cache-to: type=local,dest=.cache-new,mode=max
        file: Dockerfile
        outputs: type=local,dest=dist
        build-args: FILENAME=${{ github.sha }}.bin

    - name: extract
      uses: docker/build-push-action@v6
      with:
        push: false
        platforms: ${{ matrix.platform[0] }}
        # do not cache layers
        # cache-from: type=local,src=.cache
        # cache-to: type=local,dest=.cache-new,mode=max
        file: Dockerfile.extract
        build-args: TARGET=/app/cache
        outputs: type=local,dest=cache/sub/dir
        provenance: false

    # - name: Generate file
    #   run: |
    #     dd if=/dev/random of=cache/${{github.sha}}.bin bs=4k iflag=fullblock,count_bytes count=1M
    # # fallocate -l 1M cache/${{github.sha}}.bin

    - name: Check for cache after extract
      continue-on-error: true
      run: |
        ls -la cache
        ls -la cache/sub/dir
  
    # - name: Build with docker
    #     run: |
    #     docker buildx build . --platform=${{ matrix.platform[0] }} --progress plain -o dist -f Dockerfile.build

    # from https://github.com/ArchiveBox/ArchiveBox/blob/dev/.github/workflows/docker.yml
    # This ugly bit is necessary if you don't want your cache to grow forever
    # until it hits GitHub's limit of 5GB.
    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    # - name: Move cache
    #   run: |
    #     rm -rf .cache
    #     mv .cache-new .cache
    